kcl-lang/kcl-lang.io

.github/workflows/script-kcl.yml
docs/user_docs/getting-started/install.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/install.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.5/user_docs/getting-started/install.md
versioned_docs/version-0.4.5/user_docs/getting-started/install.md

feat: Scoop windows support
+ .github/workflows/script-kcl.yml
```release-note
None
```

feat: Scoop windows support

---

docs/user_docs/guides/ci-integration/1-github-actions.md
versioned_docs/version-0.5.0/user_docs/guides/ci-integration/1-github-actions.md

feat: add github action guide English ver.
+ docs/user_docs/guides/ci-integration/1-github-actions.md

feat: add github action guide English ver.

---

docs/user_docs/guides/working-with-konfig/1-overview.md
docs/user_docs/guides/working-with-konfig/2-structure.md
docs/user_docs/guides/working-with-konfig/3-quick-start.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-konfig/2-structure.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-konfig/3-quick-start.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.6.0/user_docs/guides/working-with-konfig/2-structure.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.6.0/user_docs/guides/working-with-konfig/3-quick-start.md
versioned_docs/version-0.6.0/user_docs/guides/working-with-konfig/1-overview.md
versioned_docs/version-0.6.0/user_docs/guides/working-with-konfig/2-structure.md
versioned_docs/version-0.6.0/user_docs/guides/working-with-konfig/3-quick-start.md

docs: update konfig documents with kpm

---

docs/tools/Ide/vs-code.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/tools/Ide/vs-code.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.6.0/tools/Ide/vs-code.md
versioned_docs/version-0.6.0/tools/Ide/vs-code.md

docs/tools/Ide/vs-code.md
fmt doc

chore: fmt doc of vscode extension

---

docs/reference/lang/tour.md
docs/user_docs/support/faq-kcl.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/tour.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-kcl.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.6.0/reference/lang/tour.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.6.0/user_docs/support/faq-kcl.md
versioned_docs/version-0.6.0/reference/lang/tour.md
versioned_docs/version-0.6.0/user_docs/support/faq-kcl.md

fix: wrong examples in tour.md and faq-acl.md

---

docs/user_docs/guides/working-with-k8s/4-publish-modules.md
docs/user_docs/guides/working-with-k8s/_4-publish-modules.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-k8s/4-publish-modules.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-k8s/_4-publish-modules.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/guides/working-with-k8s/4-publish-modules.md
versioned_docs/version-0.7.0/user_docs/guides/working-with-k8s/4-publish-modules.md

+ docs/user_docs/guides/working-with-k8s/4-publish-modules.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-k8s/4-publish-modules.md

docs: add kubernetes module publish docs

---

docs/user_docs/guides/package-management/4-how-to/7-publish_pkg_to_ah.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/package-management/4-how-to/7-publish_pkg_to_ah.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/guides/package-management/4-how-to/7-publish_pkg_to_ah.md
versioned_docs/version-0.7.0/user_docs/guides/package-management/4-how-to/7-publish_pkg_to_ah.md

add doc for 'publish kcl module to AH'

feat: add doc for 'publish kcl module to AH'

---

docs/reference/model/json.md
docs/reference/model/yaml.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/json.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/yaml.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/model/json.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/model/yaml.md
versioned_docs/version-0.7.0/reference/model/json.md
versioned_docs/version-0.7.0/reference/model/yaml.md

docs: sync latest system module documents including the json and yaml modules
+ docs/reference/model/json.md
+ docs/reference/model/yaml.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/yaml.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/json.md

docs: sync latest system module documents including the json and yaml modules

---

docs/reference/lang/spec/error.md
docs/reference/lang/spec/kcl-spec.md
docs/reference/lang/spec/modules.md
docs/reference/lang/spec/schema.md
docs/reference/lang/spec/statements.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/spec/error.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/spec/kcl-spec.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/spec/modules.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/spec/schema.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/spec/statements.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/lang/spec/error.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/lang/spec/kcl-spec.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/lang/spec/modules.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/lang/spec/schema.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/lang/spec/statements.md
versioned_docs/version-0.7.0/reference/lang/spec/error.md
versioned_docs/version-0.7.0/reference/lang/spec/kcl-spec.md
versioned_docs/version-0.7.0/reference/lang/spec/modules.md
versioned_docs/version-0.7.0/reference/lang/spec/schema.md
versioned_docs/version-0.7.0/reference/lang/spec/statements.md

+ feat: sync the latest kcl v0.7.0 grammars
+ docs/reference/lang/spec/kcl-spec.md

feat: sync the latest kcl v0.7.0 grammar documents

---

docs/user_docs/guides/working-with-kubevela/_category_.json
docs/user_docs/guides/working-with-kubevela/index.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-kubevela/_category_.json
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-kubevela/index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/guides/working-with-kubevela/_category_.json
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/guides/working-with-kubevela/index.md
versioned_docs/version-0.7.0/user_docs/guides/working-with-kubevela/_category_.json
versioned_docs/version-0.7.0/user_docs/guides/working-with-kubevela/index.md

+ docs: add kubevela integration user guide
+ docs/user_docs/guides/working-with-kubevela/index.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-kubevela/index.md

docs: add kubevela integration user guide

---

docs/user_docs/getting-started/install.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/install.md
static/script/uninstall-cli.ps1

+ feat: add uninstall scripts and documents
+ docs/user_docs/getting-started/install.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/install.md
+ static/script/uninstall-cli.ps1
+ static/script/uninstall-cli.sh

feat: add uninstall scripts and documents

---

examples/gitops/install/kcl-cmp.yaml

The shell command needs to be a single string to work properly

Fix ArgoCD plugin command args

---

blog/2023-05-30-vs-helm/index.md
examples/gitops/Makefile
examples/gitops/config/Makefile
examples/gitops/config/kubernetes_render.k
examples/gitops/config/kubernetes_render_test.k
examples/test.sh
i18n/zh-CN/docusaurus-plugin-content-blog/2023-05-30-vs-helm/index.md

fix #302 
fix: for local var example code add more unit test cases
+ blog/2023-05-30-vs-helm/index.md
+ examples/gitops/Makefile
+ examples/gitops/config/Makefile
+ examples/gitops/config/kubernetes_render.k
+ examples/test.sh
+ i18n/zh-CN/docusaurus-plugin-content-blog/2023-05-30-vs-helm/index.md
+ examples/gitops/config/kubernetes_render_test.k

fix: for local var example code add more unit test cases

---

docs/reference/model/file.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/file.md

re https://github.com/kcl-lang/kcl/pull/1157
docs: add file.abs and file.exists documents
+ docs/reference/model/file.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/file.md

docs: add file.abs and file.exists documents

---

blog/2024-04-03-newsletter/index.md
i18n/zh-CN/docusaurus-plugin-content-blog/2024-04-03-newsletter/index.md

docs: add 20240403 newsletter blogs

---

docs/reference/model/overview.md
docs/reference/model/template.md
docs/user_docs/support/faq-install.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/template.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-install.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/reference/model/file.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/reference/model/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/user_docs/support/faq-install.md
versioned_docs/version-0.8/reference/model/file.md
versioned_docs/version-0.8/user_docs/support/faq-install.md
versioned_docs/version-0.8/user_docs/support/faq-kcl.md

+ docs/reference/model/overview.md
+ docs/reference/model/template.md
+ docs/user_docs/support/faq-install.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/overview.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-install.md

docs: add builtin template function

---

docs/user_docs/support/faq-install.md
docs/user_docs/support/faq-kcl.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-install.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-kcl.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/user_docs/support/faq-install.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/user_docs/support/faq-kcl.md
versioned_docs/version-0.8/user_docs/support/faq-install.md
versioned_docs/version-0.8/user_docs/support/faq-kcl.md

+ chore: sync faq documents between the latest doc and v0.8 doc
+ docs/user_docs/support/faq-install.md
+ docs/user_docs/support/faq-kcl.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-install.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-kcl.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/user_docs/support/faq-install.md

chore: sync faq documents between the latest doc and v0.8 doc

---

docs/user_docs/getting-started/install.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/install.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/user_docs/getting-started/install.md
versioned_docs/version-0.8/user_docs/getting-started/install.md

re https://github.com/kcl-lang/kcl/issues/1169
docs: add kcl cli nix installation documents

docs: add kcl cli nix installation documents

---

docs/user_docs/guides/package-management/4-how-to/9-kpm_oci.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/package-management/4-how-to/9-kpm_oci.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/user_docs/guides/package-management/4-how-to/9-kpm_oci.md
versioned_docs/version-0.8/user_docs/guides/package-management/4-how-to/9-kpm_oci.md

docs: add oci-based registry list

docs: add oci-based registry list

---

blog/2024-04-17-newsletter/index.md
docs/reference/xlang-api/nodejs-api.md
i18n/zh-CN/docusaurus-plugin-content-blog/2024-04-17-newsletter/index.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/xlang-api/nodejs-api.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/reference/xlang-api/nodejs-api.md
versioned_docs/version-0.8/reference/xlang-api/nodejs-api.md

+ docs: add nodejs API documents

docs: add nodejs API documents

---

docs/reference/xlang-api/rust-api.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/xlang-api/rust-api.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/reference/xlang-api/rust-api.md
versioned_docs/version-0.8/reference/xlang-api/rust-api.md

+ docs: add rust api documents

docs: add rust api documents

---

examples/gitops/install/patch-argocd-repo-server.yaml

Change image entrypoint to tiny
#350 
Use docker image with tini util in argocd kcl plugin pod

Use a different image for argocd plugin

---

docs/reference/model/file.md
docusaurus.config.js
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/file.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/reference/model/file.md
versioned_docs/version-0.8/reference/model/file.md

+ feat: add more docs for the file module

feat: add more docs for the file module

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/concepts/package-and-module.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/package-management/4-how-to/5-share_your_pkg_docker.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.6/user_docs/guides/package-management/4-how-to/5-share_your_pkg_docker.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7/user_docs/concepts/package-and-module.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7/user_docs/guides/package-management/4-how-to/5-share_your_pkg_docker.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/user_docs/concepts/package-and-module.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/user_docs/guides/package-management/4-how-to/5-share_your_pkg_docker.md
versioned_docs/version-0.7/user_docs/concepts/package-and-module.md
versioned_docs/version-0.8/user_docs/concepts/package-and-module.md

+ chore: bump kpm init to kcl mod init

chore: bump kpm init to kcl mod init

---

docs/user_docs/concepts/package-and-module.md

https://github.com/kcl-lang/kcl-lang.io/blob/main/docs/user_docs/concepts/package-and-module.md
- [X ] Other
Changed kpm to kcl for consistency.
- [X ] N

docs: change kpm to kcl

---

blog/2024-05-14-lfx-guide/index.md
i18n/zh-CN/docusaurus-plugin-content-blog/2024-05-14-lfx-guide/index.md

+ chore: update LFX blog formats

chore: update LFX blog formats

---

docs/reference/lang/tour.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/tour.md

+ docs: add hyphen attribute name in language tour documents

docs: add hyphen attribute name in language tour documents

---

docusaurus.config.js

- Fixes #502
- Adds the CNCF-owned GA4 ID to the website config
- If you prefer adding Admin access to your existing measurement ID, let me know.
Related:
- #505

Configure CNCF GA4 website measurement ID

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/configuration.md

i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/configuration.md
https://github.com/kcl-lang/kcl-lang.io/blob/05c56d8a4cdc9e7531b3a0185b40f769242f46eb/i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/configuration.md?plain=1#L91
This PR fixes a small typo in the default value of `env`.  
The default value was incorrectly set to `"den"`, which should be `"dev"`.
should i also fix it in the old version? (e.g. i18n/zh-CN/docusaurus-plugin-content-docs/version-0.11/user_docs/guides/configuration.md)

fix(typo): correct default value from 'den' to 'dev'

---

docs/tools/Ide/helix.md
docs/tools/Ide/index.md

feat: add Helix IDE configuration instructions
