- blog/2022-11-29-kcl-rewrite-with-rust/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2022-11-29-kcl-rewrite-with-rust/index.md
feat: add kcl rewrite with rust blog.
```release-note
None
```
> feat: add kcl rewrite with rust blog.

- docs/reference/model/manifests.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/manifests.md
feat: add manifests yaml_system module documents.
```release-note
None
```
> feat: add manifests yaml system module documents.

- .github/workflows/script-kcl.yml
> test: test windows (just for test)

- .github/workflows/script-kcl.yml
- static/script/install.sh
re: https://github.com/KusionStack/kusionstack.io/pull/210
feat: add KCLVM PATH set in install scripts
```release-note
None
```
> feat: add KCLVM PATH set in install scripts

- .github/workflows/script-kcl.yml
chore: update kcl linux test scripts.
```release-note
None
```
> chore: update kcl linux test scripts.

- .github/workflows/script-kusion.yml
test: add kcl testing in kusion scripts and add sudo in macOS tests
```release-note
None
```
> test: add kcl testing in kusion scripts and add sudo in macOS tests

- docs/user_docs/support/faq-kcl.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-kcl.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.3/user_docs/support/faq-kcl.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.4/user_docs/support/faq-kcl.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.5/user_docs/support/faq-kcl.md
- versioned_docs/version-0.4.3/user_docs/support/faq-kcl.md
- versioned_docs/version-0.4.4/user_docs/support/faq-kcl.md
- versioned_docs/version-0.4.5/user_docs/support/faq-kcl.md
feat: add kcl any type faq.feat: add kcl any type faq.
```release-note
None
```
> feat: add kcl any type faq.

- docs/tools/Ide/vs-code.md
- docs/user_docs/getting-started/install.md
- versioned_docs/version-0.4.6/tools/Ide/vs-code.md
- versioned_docs/version-0.4.6/user_docs/getting-started/install.md
IDE doc
update getting_started / install VS Code
```release-note
None
```
> doc: update getting-started/install VS Code and fix some typo

- blog/2023-04-27-new-version-feature-interpretation-kclvm-go-feature-overview/index.md
> chorm : add kclvm-go-feature-overview

- i18n/zh-CN/docusaurus-plugin-content-blog/2023-04-27-new-version-feature-interpretation-kclvm-go-feature-overview/index.md
>  chorm : add kclvm-go-feature-overview zh-CN

- docs/user_docs/getting-started/intro.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/intro.md
docs: refine kcl intro documents.
```release-note
None
```
> docs: refine kcl intro documents.

- examples/mutation/Makefile
- examples/mutation/kcl.yaml
- examples/mutation/transformer.k
- examples/validation/Makefile
- examples/validation/data.json
- examples/validation/schema.k
feat: add mutation and validation examples.
```release-note
None
```
> feat: add mutation and validation examples.

- docs/user_docs/getting-started/intro.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/intro.md
docs: polish kcl intro documents.
```release-note
None
```
> docs: polish kcl intro documents.

- docs/user_docs/guides/abstraction.md
- docs/user_docs/guides/working-with-konfig/4-best-practice.md
docs: add abstraction documents for KCL.
```release-note
None
```
> docs: add abstraction documents for KCL.

- .github/workflows/example-e2e-test.yml
- docs/user_docs/guides/configuration.md
- docs/user_docs/guides/validation.md
- examples/configuration/Makefile
- examples/configuration/db.k
- examples/configuration/nginx.k
- examples/test.sh
feat: refine kcl user guide en ver and add e2e tests
+ examples/configuration/
```release-note
None
```
> feat: refine kcl user guide en ver and add e2e tests

- .github/workflows/example-e2e-test.yml
> fix: example e2e test scripts.

- docs/user_docs/guides/automation.md
- examples/automation/Makefile
- examples/automation/main.k
- examples/test.sh
- versioned_docs/version-0.4.6/user_docs/guides/automation.md
- versioned_docs/version-0.5.0/user_docs/guides/automation.md
docs: polish automation documents.
```release-note
None
```
> docs: polish automation documents.

- docs/user_docs/guides/automation.md
- docs/user_docs/guides/configuration.md
- docs/user_docs/guides/data-integration.md
- docs/user_docs/guides/schema-definition.md
- docs/user_docs/guides/validation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/configuration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/schema-definition.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/validation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.6/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.6/user_docs/guides/configuration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.6/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.6/user_docs/guides/schema-definition.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.6/user_docs/guides/validation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/configuration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/schema-definition.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/validation.md
- versioned_docs/version-0.4.6/user_docs/guides/automation.md
- versioned_docs/version-0.4.6/user_docs/guides/configuration.md
- versioned_docs/version-0.4.6/user_docs/guides/data-integration.md
- versioned_docs/version-0.4.6/user_docs/guides/schema-definition.md
- versioned_docs/version-0.4.6/user_docs/guides/validation.md
- versioned_docs/version-0.5.0/user_docs/guides/automation.md
- versioned_docs/version-0.5.0/user_docs/guides/configuration.md
- versioned_docs/version-0.5.0/user_docs/guides/data-integration.md
- versioned_docs/version-0.5.0/user_docs/guides/schema-definition.md
- versioned_docs/version-0.5.0/user_docs/guides/validation.md
docs: update user guide zh-cn docs
```release-note
None
```
> docs: update user guide zh-cn docs

- docs/user_docs/guides/working-with-konfig/4-best-practice.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/codelab/simple.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-konfig/4-best-practice.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/working-with-konfig/4-best-practice.md
- versioned_docs/version-0.5.0/user_docs/guides/working-with-konfig/4-best-practice.md
docs: polish konfig best practice documents.
```release-note
None
```
> docs: polish konfig best practice documents.

- versioned_docs/version-0.5.0/user_docs/getting-started/install.md
related to #4 
versioned_docs/version-0.5.0/user_docs/getting-started/install.md
update intellij idea KCL plugin installation guide
```release-note
None
```
> update intellij idea KCL plugin installation guide

- docs/tools/Ide/vs-code.md
- docs/user_docs/getting-started/install.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/tools/Ide/vs-code.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/install.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/tools/Ide/vs-code.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/getting-started/install.md
- static/script/install.sh
- versioned_docs/version-0.5.0/tools/Ide/vs-code.md
- versioned_docs/version-0.5.0/user_docs/getting-started/install.md
- versioned_docs/version-0.5.0/user_docs/guides/working-with-k8s/argocd.md
docs: polish install documents
```release-note
None
```
> docs: polish install documents

- docs/user_docs/guides/gitops/1-quick-start.md
- docs/user_docs/guides/gitops/_category_.json
- docs/user_docs/guides/working-with-k8s/argocd.md
- examples/kubernetes/argocd/patch-argocd-repo-server.yaml
- install.yaml
- kcl-cmp.yaml
- patch-argocd-cm.yaml
- patch-argocd-cm.yaml.1
- patch-argocd-repo-server.yaml
- temp-cmp.yaml
feat: add KCL GitOps examples
+ docs/user_docs/guides/gitops/1-quick-start.md
```release-note
None
```
> WIP: KCL GitOps example

- .github/workflows/deploy.yml
- .github/workflows/example-e2e-test.yml
- .github/workflows/install-kcl.yml
- README.md
- docs/user_docs/guides/gitops/1-quick-start.md
- install-2.7.4.yaml
> feat: add gitops examples

- docs/user_docs/guides/package-management/2-installation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/package-management/2-installation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.6/user_docs/guides/package-management/2-installation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/package-management/2-installation.md
- versioned_docs/version-0.4.6/user_docs/guides/package-management/2-installation.md
- versioned_docs/version-0.5.0/user_docs/guides/package-management/2-installation.md
> fix: update 'go install kpm'.

- docs/user_docs/guides/package-management/4-share_your_pkg.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/package-management/4-share_your_pkg.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/package-management/4-share_your_pkg.md
- versioned_docs/version-0.5.0/user_docs/guides/package-management/4-share_your_pkg.md
> feat: add user guides for 'kpm push'.

- docs/tools/Ide/vs-code.md
- versioned_docs/version-0.5.0/tools/Ide/vs-code.md
docs/tools/Ide/vs-code.md
update vscode doc, add hints about dependent plugins for enhance diagnostic
```release-note
None
```
> doc: update vscode docs

- i18n/zh-CN/docusaurus-plugin-content-docs/current/tools/Ide/vs-code.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/tools/Ide/vs-code.md
chore: sync vs-code documents to latest.
> chore: sync vs-code documents to latest.

- docs/tools/cli/openapi/quick-start.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/tools/cli/openapi/quick-start.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/tools/cli/openapi/quick-start.md
- versioned_docs/version-0.5.0/tools/cli/openapi/quick-start.md
docs/tools/cli/openapi/quick-start.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/tools/cli/openapi/quick-start.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/tools/cli/openapi/quick-start.md
versioned_docs/version-0.5.0/tools/cli/openapi/quick-start.md
update kcl-openapi installation approaches:
- fix wrong install script
- update verify installation script to `kcl-openapi -v`
- fix break section links in CN version
> update kcl-openapi installation approaches

- .github/workflows/install-kcl.yml
- Makefile
- docs/tools/cli/openapi/quick-start.md
- docs/user_docs/getting-started/install.md
- docs/user_docs/getting-started/kcl-quick-start.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/install.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/kcl-quick-start.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/getting-started/install.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/getting-started/kcl-quick-start.md
- versioned_docs/version-0.5.0/user_docs/getting-started/install.md
- versioned_docs/version-0.5.0/user_docs/getting-started/kcl-quick-start.md
chore: bump install namespace to kcl from kclvm
> chore: bump install namespace to kcl from kclvm

- docs/reference/lang/tour.md
- docs/tools/cli/kcl/overview.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/tour.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/tools/cli/kcl/overview.md
> docs: add cli config docs

- docusaurus.config.js
- package-lock.json
- package.json
feat: add google analytics plugin
+ docusaurus.config.js
> feat: add google analytics plugin

- docs/user_docs/guides/secret-management/1-vault.md
- docs/user_docs/guides/secret-management/_category_.json
- docs/user_docs/guides/working-with-kusion/_category_.json
- examples/secret-management/vault/kcl.mod
- examples/secret-management/vault/main.k
- i18n/en/docusaurus-plugin-content-docs/current.json
- i18n/en/docusaurus-plugin-content-docs/version-0.5.1.json
- i18n/zh-CN/docusaurus-plugin-content-docs/current.json
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/secret-management/1-vault.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/secret-management/_category_.json
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-kusion/_category_.json
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0.json
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.1.json
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.1/user_docs/guides/secret-management/1-vault.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.1/user_docs/guides/secret-management/_category_.json
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.1/user_docs/guides/working-with-kusion/_category_.json
- package-lock.json
- package.json
- versioned_docs/version-0.5.1/user_docs/guides/secret-management/1-vault.md
- versioned_docs/version-0.5.1/user_docs/guides/secret-management/_category_.json
- versioned_docs/version-0.5.1/user_docs/guides/working-with-kusion/_category_.json
feat: add vault integration documents and secret management categories.
+ docs/user_docs/guides/secret-management/1-vault.md
> feat: add vault integration documents and secret management categories.

- docusaurus.config.js
- i18n/en/code.json
- i18n/zh-CN/code.json
- package-lock.json
- package.json
- src/css/custom.css
- src/pages/index.tsx
- tailwind.config.js
feat: add subscribe form at index page
chore: format all css files
+ src/pages/index.tsx
> feat: add subscribe form at index page

- docs/user_docs/guides/package-management/5-share_your_pkg_docker.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/package-management/5-share_your_pkg_docker.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/package-management/5-share_your_pkg_docker.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.1/user_docs/guides/package-management/5-share_your_pkg_docker.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.2/user_docs/guides/package-management/5-share_your_pkg_docker.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.3/user_docs/guides/package-management/5-share_your_pkg_docker.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.4/user_docs/guides/package-management/5-share_your_pkg_docker.md
- versioned_docs/version-0.5.0/user_docs/guides/package-management/5-share_your_pkg_docker.md
- versioned_docs/version-0.5.1/user_docs/guides/package-management/5-share_your_pkg_docker.md
- versioned_docs/version-0.5.2/user_docs/guides/package-management/5-share_your_pkg_docker.md
- versioned_docs/version-0.5.3/user_docs/guides/package-management/5-share_your_pkg_docker.md
- versioned_docs/version-0.5.4/user_docs/guides/package-management/5-share_your_pkg_docker.md
> feat: user guide for 'kpm push' to docker.io.

- docs/user_docs/concepts/type-and-definition.md
feat: add type and definition concept documents
+ docs/user_docs/concepts/type-and-definition.md
> feat: add type and definition concept documents

- blog/2023-08-23-biweekly-newsletter/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2023-08-23-biweekly-newsletter/index.md
feat: add 2nd biweekly newsletter blogs
+ blog/2023-08-23-biweekly-newsletter/index.md
+ i18n/zh-CN/docusaurus-plugin-content-blog/2023-08-23-biweekly-newsletter/index.md
> feat: add 2nd biweekly newsletter blogs

- docs/user_docs/guides/working-with-k8s/3-mutate-manifests/6-kcl-operator.md
- versioned_docs/version-0.5.5/user_docs/guides/working-with-k8s/3-mutate-manifests/6-kcl-operator.md
+ feat: add kcl operator documents
+ docs/user_docs/guides/working-with-k8s/3-mutate-manifests/6-kcl-operator.md
> feat: add kcl operator documents

- docusaurus.config.js
- i18n/en/docusaurus-theme-classic/navbar.json
feat: add packages navbar.
+ docusaurus.config.js
+ i18n/en/docusaurus-theme-classic/navbar.json
> feat: add packages navbar.

- blog/2023-09-06-biweekly-newsletter/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2023-09-06-biweekly-newsletter/index.md
feat: add 2023-09-06-biweekly-newsletter blogs
+ blog/2023-09-06-biweekly-newsletter/index.md
+ i18n/zh-CN/docusaurus-plugin-content-blog/2023-09-06-biweekly-newsletter/index.md
> feat: add 2023-09-06-biweekly-newsletter blogs

- versioned_docs/version-0.6.0/user_docs/guides/working-with-k8s/1-adopt-from-kubernetes.md
> fix format error

- docusaurus.config.js
- i18n/en/code.json
- i18n/en/docusaurus-theme-classic/footer.json
- i18n/zh-CN/code.json
- src/pages/index.tsx
feat: add kcl cncf sandbox info and the linux foundation copyright.
+ sandbox info: We are a Cloud Native Computing Foundation sandbox project
+ linux foundation copyright: The Linux Foundation. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks.
+ docusaurus.config.js
+ src/pages/index.tsx
+ i18n/zh-CN/code.json
> feat: add kcl cncf sandbox info and the linux foundation copyright.

- .gitignore
- docs/user_docs/guides/_working-with-terraform/1-overview.md
- docs/user_docs/guides/_working-with-terraform/3-coverter.md
- docs/user_docs/guides/working-with-terraform/3-validation.md
- docs/user_docs/guides/working-with-terraform/_1-adopt-from-terraform.md
- docs/user_docs/guides/working-with-terraform/_2-abstraction.md
- docs/user_docs/guides/working-with-terraform/_category_.json
- examples/terraform/validation/main.k
- examples/terraform/validation/main.policy.failure.k
- examples/terraform/validation/main.tf
- examples/terraform/validation/tfplan.json
- versioned_docs/version-0.6.0/user_docs/guides/working-with-terraform/3-validation.md
- versioned_docs/version-0.6.0/user_docs/guides/working-with-terraform/_1-adopt-from-terraform.md
- versioned_docs/version-0.6.0/user_docs/guides/working-with-terraform/_2-abstraction.md
- versioned_docs/version-0.6.0/user_docs/guides/working-with-terraform/_category_.json
+ docs: add terraform plan policy user guide with kcl
+ versioned_docs/version-0.6.0/user_docs/guides/working-with-terraform/3-validation.md
+ examples/terraform/validation
> docs: add terraform plan policy user guide with kcl

- blog/2023-10-11-biweekly-newsletter/index.md
- blog/2023-10-25-biweekly-newsletter/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2023-10-25-biweekly-newsletter/index.md
doc: biweekly-10-25 en version
> doc: biweekly-10-25 en version

- docs/reference/lang/tour.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/tour.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.6.0/reference/lang/tour.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/lang/tour.md
- versioned_docs/version-0.6.0/reference/lang/tour.md
- versioned_docs/version-0.7.0/reference/lang/tour.md
docs: add index signature alias self reference in the schema
> docs: add index signature alias self reference in the schema

- docs/user_docs/guides/working-with-k8s/3-mutate-manifests/1-kubectl-kcl-plugin.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-k8s/3-mutate-manifests/1-kubectl-kcl-plugin.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/guides/working-with-k8s/3-mutate-manifests/1-kubectl-kcl-plugin.md
- versioned_docs/version-0.7.0/user_docs/guides/working-with-k8s/3-mutate-manifests/1-kubectl-kcl-plugin.md
docs: use oci registry for kubernetes mutation and validation examples
+ docs/user_docs/guides/working-with-k8s/3-mutate-manifests/1-kubectl-kcl-plugin.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-k8s/3-mutate-manifests/1-kubectl-kcl-plugin.md
> docs: use oci registry for kubernetes mutation and validation examples

- .github/workflows/install-kusion.yml
chore: remove kcl installation in kusion test scripts.
+ .github/workflows/install-kusion.yml
> chore: remove kcl installation in kusion test scripts.

- examples/data-integration/main.k
https://kcl-lang.io/zh-CN/docs/user_docs/guides/automation
补充网站doc中的实例文件main.k，添加路径为examples/data-integration/main.k
> feat:add main.k

- static/script/install-cli.ps1
- static/script/install-cli.sh
fix: install scripts for kcl new CLI (v0.7.0 ver.)
+ static/script/install-cli.sh
+ static/script/install-cli.ps1
+ .github/workflows/install-kcl.yml
> fix: install scripts for kcl new CLI (v0.7.0 ver.)

- static/script/install-kcl-lsp.ps1
- static/script/install-kcl-lsp.sh
feat: add kcl language server binary install scripts
+ static/script/install-kcl-lsp.ps1
+ static/script/install-kcl-lsp.sh
> feat: add kcl language server binary install scripts

- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.6/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.1/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.2/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.3/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.4/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.5/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.6/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.6.0/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/guides/automation.md
> fix: broken link

- docs/user_docs/guides/working-with-k8s/3-mutate-manifests/1-kubectl-kcl-plugin.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/working-with-k8s/3-mutate-manifests/1-kubectl-kcl-plugin.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/guides/working-with-k8s/3-mutate-manifests/1-kubectl-kcl-plugin.md
- versioned_docs/version-0.7.0/user_docs/guides/working-with-k8s/3-mutate-manifests/1-kubectl-kcl-plugin.md
> fix: kubectl doc

- docs/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.6/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.1/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.2/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.3/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.4/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.5/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.6/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.6.0/user_docs/guides/data-integration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/guides/data-integration.md
- versioned_docs/version-0.4.6/user_docs/guides/data-integration.md
- versioned_docs/version-0.5.0/user_docs/guides/data-integration.md
- versioned_docs/version-0.5.1/user_docs/guides/data-integration.md
- versioned_docs/version-0.5.2/user_docs/guides/data-integration.md
- versioned_docs/version-0.5.3/user_docs/guides/data-integration.md
- versioned_docs/version-0.5.4/user_docs/guides/data-integration.md
- versioned_docs/version-0.5.5/user_docs/guides/data-integration.md
- versioned_docs/version-0.5.6/user_docs/guides/data-integration.md
- versioned_docs/version-0.6.0/user_docs/guides/data-integration.md
- versioned_docs/version-0.7.0/user_docs/guides/data-integration.md
> fix: doc output

- blog/2023-11-23-biweekly-newsletter/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2023-11-23-biweekly-newsletter/index.md
> fix: artifact kcl module links

- docs/user_docs/getting-started/install.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/install.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/getting-started/install.md
- versioned_docs/version-0.7.0/user_docs/getting-started/install.md
+ docs/user_docs/getting-started/install.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/install.md
> docs: add kcl language server install guide

- docs/tools/cli/kcl/overview.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/tools/cli/kcl/overview.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/tools/cli/kcl/overview.md
- versioned_docs/version-0.7.0/tools/cli/kcl/overview.md
+ feat: kcl cli v0.7 overview documents
+ docs/tools/cli/kcl/overview.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/tools/cli/kcl/overview.md
> feat: kcl cli v0.7 overview documents

- docs/tools/cli/kcl/overview.md
- docs/tools/cli/kcl/run.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/tools/cli/kcl/overview.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/tools/cli/kcl/run.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/tools/cli/kcl/overview.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/tools/cli/kcl/run.md
- versioned_docs/version-0.7.0/tools/cli/kcl/overview.md
- versioned_docs/version-0.7.0/tools/cli/kcl/run.md
feat: add cli overview and run command documents.
+ docs/tools/cli/kcl/overview.md
+ docs/tools/cli/kcl/run.md
> feat: add cli overview and run command documents.

- blog/2023-12-07-biweekly-newsletter/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2023-12-07-biweekly-newsletter/index.md
+ docs: add 2023-12-07 biweekly newsletter blogs
+ blog/2023-12-07-biweekly-newsletter/index.md
+ i18n/zh-CN/docusaurus-plugin-content-blog/2023-12-07-biweekly-newsletter/index.md
> docs: add 2023-12-07 biweekly newsletter blogs

- .github/workflows/docsearch.yml
- blog/2023-12-21-biweekly-newsletter/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2023-12-21-biweekly-newsletter/index.md
- package-lock.json
- package.json
- src/pages/index.module.css
- src/pages/index.tsx
+ chore: format all document
+ feat: use lazy load image at index pages
+ ci: add doc search scraper cron job 
+ .github/workflows/docsearch.yml
+ src/pages/index.module.css
+ src/pages/index.tsx
> refactor: index page and documents

- docs/user_docs/guides/working-with-k8s/3-mutate-manifests/7-crossplane-kcl-function.md
- i18n/en/docusaurus-plugin-content-docs/current.json
- i18n/en/docusaurus-plugin-content-docs/version-0.7.0.json
- versioned_docs/version-0.7.0/user_docs/guides/working-with-k8s/3-mutate-manifests/7-crossplane-kcl-function.md
feat: add crossplane kcl function user guides
+ docs/user_docs/guides/working-with-k8s/3-mutate-manifests/7-crossplane-kcl-function.md
> feat: add crossplane kcl function user guides

- blog/2024-01-04-biweekly-newsletter/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2024-01-04-biweekly-newsletter/index.md
- versioned_docs/version-0.7.0/user_docs/guides/working-with-k8s/3-mutate-manifests/7-crossplane-kcl-function.md
+ feat: add biweekly-newsletter-2024-01-04
+ blog/2024-01-04-biweekly-newsletter/index.md
+ i18n/zh-CN/docusaurus-plugin-content-blog/2024-01-04-biweekly-newsletter/index.md
> feat: add biweekly-newsletter-2024-01-04

- docs/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.3/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.4/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.5/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.4.6/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.0/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.1/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.2/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.3/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.4/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.5/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.5.6/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.6.0/reference/lang/spec/kcl-spec.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.4.3/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.4.4/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.4.5/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.4.6/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.5.0/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.5.1/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.5.2/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.5.3/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.5.4/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.5.5/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.5.6/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.6.0/reference/lang/spec/kcl-spec.md
- versioned_docs/version-0.7.0/reference/lang/spec/kcl-spec.md
refactor: enhance kcl operator precedence table
+ docs/reference/lang/spec/kcl-spec.md
> refactor: enhance kcl operator precedence table

- docs/user_docs/guides/package-management/4-how-to/8-kcl_mod.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/package-management/4-how-to/8-kcl_mod.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/guides/package-management/4-how-to/8-kcl_mod.md
- versioned_docs/version-0.7.0/user_docs/guides/package-management/4-how-to/8-kcl_mod.md
> feat: add docs for kcl.mod

- docs/user_docs/guides/package-management/4-how-to/9-kpm_oci.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/package-management/4-how-to/8-kcl_mod.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/package-management/4-how-to/9-oci_reg_supports.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/guides/package-management/4-how-to/8-kcl_mod.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/guides/package-management/4-how-to/9-oci_reg_supports.md
- versioned_docs/version-0.7.0/user_docs/guides/package-management/4-how-to/9-kpm_oci.md
> feat: add docs for supporting OCI registry

- docs/reference/lang/spec/schema.md
- docs/reference/lang/tour.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/spec/modules.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/spec/schema.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/tour.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/lang/spec/modules.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/lang/spec/schema.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/lang/tour.md
- versioned_docs/version-0.7.0/reference/lang/spec/schema.md
- versioned_docs/version-0.7.0/reference/lang/tour.md
fix #249 
fix: error regex expressions in the index signature examples
+ docs/reference/lang/spec/schema.md
+ docs/reference/lang/tour.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/tour.md
> fix: error regex expressions in the index signature examples

- docs/tools/cli/package-management/command-reference/11.update.md
> doc: added kcl mod update documentation

- blog/2024-01-04-biweekly-newsletter/index.md
+ docs: refactor crossplane kcl function blogs
+ blog/2024-01-04-biweekly-newsletter/index.md
> docs: refactor crossplane kcl function blogs

- docs/reference/plugin/overview.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/plugin/overview.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/reference/plugin/overview.md
- versioned_docs/version-0.7.0/reference/plugin/overview.md
- versioned_docs/version-0.7.0/tools/cli/package-management/command-reference/11.update.md
re #256 
+ chore: update kcl-plugin documents
> chore: update kcl-plugin documents

- docs/user_docs/support/faq-kcl.md
fix #145 
support/faq-kcl.md
PR output:
Need reviews @Peefy
> added hash/md5 support example

- docs/user_docs/support/faq-kcl.md
> added deduplicate str lists example

- docs/user_docs/guides/configuration.md
- examples/configuration/db.k
> Fix: typo in document of Configuration

- docs/user_docs/support/faq-kcl.md
> Updated faq-kcl.md with disableNone feature

- versioned_docs/version-0.7.0/user_docs/support/faq-kcl.md
> add convert JSON structures to schemas

- versioned_docs/version-0.7.0/user_docs/support/faq-kcl.md
> added return types of json and yaml decode functions 

- versioned_docs/version-0.7.0/user_docs/support/faq-kcl.md
> added the difference between schema and lambda function

- docs/user_docs/support/faq-kcl.md
> doc: added schema faq

- blog/2024-02-22-newsletter/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2024-02-22-newsletter/index.md
+ blog/2024-02-22-newsletter/index.md
+ i18n/zh-CN/docusaurus-plugin-content-blog/2024-02-22-newsletter/index.md
> docs: add 2024-02-22 blogs

- docs/reference/xlang-api/go-api.md
- docs/reference/xlang-api/rest-api.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/xlang-api/go-api.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/xlang-api/rest-api.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-kcl.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/support/faq-kcl.md
+ feat: add kcl v0.8 API documents
+ docs/reference/xlang-api/go-api.md
+ docs/reference/xlang-api/rest-api.md
> feat: add kcl v0.8 API documents

- docs/tools/cli/package-management/command-reference/2.add.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/tools/cli/package-management/command-reference/2.add.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/tools/cli/package-management/command-reference/2.add.md
- versioned_docs/version-0.7.0/tools/cli/package-management/command-reference/2.add.md
+ docs/tools/cli/package-management/command-reference/2.add.md
> fix: kcl mod add reference documents

- docs/user_docs/support/faq-kcl.md
> dict & schema conversion faq added

- docs/reference/model/file.md
- docs/reference/model/overview.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/file.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/overview.md
re https://github.com/kcl-lang/kcl/issues/1049
> feat: add docs for filesystem builtin functions

- docs/user_docs/support/faq-kcl.md
> added usage of r prefix and string interpolation

- docs/reference/model/crypto.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/crypto.md
+ docs: add crypto.uuid and crypto.filesha256 documents
+ docs/reference/model/crypto.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/crypto.md
> docs: add crypto.uuid and crypto.filesha256 documents

- blog/2024-02-05-lfx-guide/index.md
- docs/reference/lang/spec/codestyle.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2024-02-05-lfx-guide/index.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/spec/codestyle.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8.0/reference/lang/spec/codestyle.md
- versioned_docs/version-0.8.0/reference/lang/spec/codestyle.md
Close #183 
+ docs/reference/lang/spec/codestyle.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/spec/codestyle.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8.0/reference/lang/spec/codestyle.md
+ versioned_docs/version-0.8.0/reference/lang/spec/codestyle.md
> docs: add code style for schema index signatures

- blog/2024-03-04-crossplane-marketplace-kcl/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2024-03-04-crossplane-marketplace-kcl/index.md
fix: managed resource typo
+ blog/2024-03-04-crossplane-marketplace-kcl/index.md
+ i18n/zh-CN/docusaurus-plugin-content-blog/2024-03-04-crossplane-marketplace-kcl/index.md
> fix: managed resource typo

- blog/2024-03-06-kcl-0.8.0-release/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2024-03-06-kcl-0.8.0-release/index.md
+ docs: polish KCL v0.8 release blogs
> docs: polish KCL v0.8 release blogs

- docs/user_docs/guides/package-management/4-how-to/9-kpm_oci.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/package-management/4-how-to/9-kpm_oci.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.7.0/user_docs/guides/package-management/4-how-to/9-kpm_oci.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8.0/user_docs/guides/package-management/4-how-to/9-kpm_oci.md
- versioned_docs/version-0.7.0/user_docs/guides/package-management/4-how-to/9-kpm_oci.md
- versioned_docs/version-0.8.0/user_docs/guides/package-management/4-how-to/9-kpm_oci.md
> feat: add env docs for configure the OCI registry

- blog/2024-01-04-biweekly-newsletter/index.md
- docs/user_docs/guides/working-with-k8s/3-mutate-manifests/7-crossplane-kcl-function.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2024-01-04-biweekly-newsletter/index.md
- versioned_docs/version-0.7/user_docs/guides/working-with-k8s/3-mutate-manifests/7-crossplane-kcl-function.md
- versioned_docs/version-0.8/user_docs/guides/working-with-k8s/3-mutate-manifests/7-crossplane-kcl-function.md
+ chore: bump crossplane function kcl image
+ blog/2024-01-04-biweekly-newsletter/index.md
+ docs/user_docs/guides/working-with-k8s/3-mutate-manifests/7-crossplane-kcl-function.md
+ i18n/zh-CN/docusaurus-plugin-content-blog/2024-01-04-biweekly-newsletter/index.md
+ versioned_docs/version-0.7/user_docs/guides/working-with-k8s/3-mutate-manifests/7-crossplane-kcl-function.md
+ versioned_docs/version-0.8/user_docs/guides/working-with-k8s/3-mutate-manifests/7-crossplane-kcl-function.md
> chore: bump crossplane function kcl image

- blog/2024-04-03-newsletter/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2024-04-03-newsletter/index.md
> fix: add contributions

- docs/user_docs/support/faq-install.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-install.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/reference/model/file.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/user_docs/support/faq-install.md
- versioned_docs/version-0.8/reference/model/file.md
- versioned_docs/version-0.8/user_docs/support/faq-install.md
- versioned_docs/version-0.8/user_docs/support/faq-kcl.md
+ faq: add kcl start in docker containers
+ docs/user_docs/support/faq-install.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-install.md
> faq: add kcl start in docker containers

- blog/2024-04-17-newsletter/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2024-04-17-newsletter/index.md
+ blog/2024-04-17-newsletter/index.md
+ i18n/zh-CN/docusaurus-plugin-content-blog/2024-04-17-newsletter/index.md
> docs: add 0417 newsletter blogs

- docs/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/automation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/user_docs/guides/automation.md
- versioned_docs/version-0.8/user_docs/guides/automation.md
+ docs: update the override spec form
> docs: update the override spec form

- .github/workflows/install-kcl.yml
+ ci: fix kcl installation ci test scripts
+ .github/workflows/install-kcl.yml
> ci: fix kcl installation ci test scripts

- docs/reference/model/file.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/file.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-0.8/reference/model/file.md
- versioned_docs/version-0.8/reference/model/file.md
+ docs: update file.delete function docs
> docs: update file.delete function docs

- blog/2024-05-14-lfx-guide/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2024-05-14-lfx-guide/index.md
> feat: add guide for LFX Term 2

- blog/2024-05-15-newsletter/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2024-05-15-newsletter/index.md
+ docs: add 2024-05-15 newsletter blogs
+ blog/2024-05-15-newsletter/index.md
+ i18n/zh-CN/docusaurus-plugin-content-blog/2024-05-15-newsletter/index.md
> docs: add 2024-05-15 newsletter blogs

- docs/user_docs/support/faq-kcl.md
- versioned_docs/version-0.8/user_docs/support/faq-kcl.md
fix #368 
docs(faq): add more instructions and examples for the function type annotation
> docs(faq): add more instructions and examples for the function type annotation

- docs/user_docs/support/faq-kcl.md
+ docs(faq): package path env set
> docs(faq): package path cache env set

- .github/workflows/install-kcl-lsp.yml
- .github/workflows/install-kcl.yml
> fix: rm macos-12 in github action

- blog/2024-12-24-kcl-0.11.0-release/index.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2024-12-24-kcl-0.11.0-release/index.md
> feat: add more community contributors
